### ISSUE TITLE
typo in import statement?

### ISSUE THREAD

**Issue by daniel309** [IBM/analytics-accelerator-capture-replay#2]
Hi @cjchangGit, just saw the blank between the '.' and the '*' at https://github.com/IBM/analytics-accelerator-capture-replay/blob/9fe7b0a2261417dc58914811a1029be65524510f/SQLHistorySummaryV75.java#L2 and https://github.com/IBM/analytics-accelerator-capture-replay/blob/9fe7b0a2261417dc58914811a1029be65524510f/SQLHistorySummaryV75.java#L3

not sure if this is intentional, pls close this issue if it is...

congrats on the OSS release 👍

**Comment by cjchangGit** [comment]
thanks Daniel, just fixed this typo
